if __name__ == "__main__":
    flight_booking = FlightBooking()
    flight_booking.open_browser('https://www.cleartrip.com/')
    flight_booking.select_round_trip()
    flight_booking.select_city('FromTag', 'fra')
    flight_booking.select_city('ToTag', 'san')
    flight_booking.select_date(9, 2)
    flight_booking.driver.find_element(By.CSS_SELECTOR, 'a.nextMonth').click()
    flight_booking.select_date(11, 21)
    flight_booking.select_travel_details(adults=2, children=3, travel_class='Premium Economy')
    flight_booking.search_flights()
    flight_booking.change_currency('US Dollar')
    flight_booking.select_flight()
    flight_booking.continue_booking()
    flight_booking.save_screenshot('error_msg.png')
